stages:
  - build
  - package
  - publish

variables:
  VERSION: "0.0.0-development"

build_maven:
  stage: build
  script:
    - cd JDBC.NET.Bridge
    - mvn clean package
  artifacts:
    paths:
      - JDBC.NET.Bridge/target/
  tags:
    - windows

package_nuget:
  stage: package
  script:
    - cd JDBC.NET.Data
    - dotnet pack --configuration Release -p:Version=$VERSION -o "../artifacts"
  artifacts:
    paths:
      - artifacts
  tags:
    - windows
    
publish_nuget:
  stage: publish
  script:
    - echo "Pushing JDBC.NET version $VERSION"
    - dotnet nuget push "artifacts/DATPROF.JDBC.NET.Data.$VERSION.nupkg" --api-key "$NUGET_API_KEY" --source "$NEXUS_URL"  --no-symbols
  when: manual
  tags:
    - windows  